package main

// Baseline export: produces a YAML snapshot of every probe's current
// state, intended as the reference file the runtime self-check
// (separate, daemon-side, deferred to a future feature) will read
// to detect hardware-config drift.
//
// Format: hand-rolled YAML, no external dependency. The structure
// is shallow enough that a 50-line writer is simpler than pulling
// in gopkg.in/yaml.v3.
//
//   generated: 2026-05-14T22:30:00-03:00
//   host: cartman
//   tool_version: zerotx-bench D2+E
//   probes:
//     - id: rtc-ds3231
//       name: DS3231 RTC
//       category: I2C
//       expected_status: pass
//       details:
//         i2c bus: "1"
//         i2c address: "0x68"
//         ...
//     - id: gps-ublox
//       ...
//
// The "expected_status" field is whatever the probe reported when
// the baseline was taken. The runtime self-check enforces it: a
// probe that was pass at baseline time must be pass at boot; a
// probe that was skip is allowed to skip; a probe that was fail
// raises an alert. Drift detection is left to the consumer.

import (
	"context"
	"fmt"
	"net/http"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"
)

const defaultBaselinePath = "./hardware-baseline.yaml"

// handleBaseline serves the baseline export endpoint:
//
//	POST /api/baseline?path=PATH  - run all probes, write YAML to PATH
//	                                (default ./hardware-baseline.yaml),
//	                                return {path, yaml, probe_count}
//	GET  /api/baseline?path=PATH  - return the contents of PATH if it
//	                                exists, 404 otherwise
//
// The path query parameter is optional; defaults to a fixed path in
// the current working directory. Absolute paths are honored; relative
// paths are resolved against cwd.
func handleBaseline(r *Registry) http.HandlerFunc {
	return func(w http.ResponseWriter, req *http.Request) {
		path := req.URL.Query().Get("path")
		if path == "" {
			path = defaultBaselinePath
		}
		switch req.Method {
		case http.MethodGet:
			data, err := os.ReadFile(path)
			if err != nil {
				if os.IsNotExist(err) {
					http.Error(w, "no baseline at "+path, http.StatusNotFound)
					return
				}
				http.Error(w, err.Error(), http.StatusInternalServerError)
				return
			}
			writeJSON(w, http.StatusOK, map[string]any{
				"path": path,
				"yaml": string(data),
			})
		case http.MethodPost:
			yaml, count := generateBaseline(req.Context(), r)
			abs, _ := filepath.Abs(path)
			if err := os.WriteFile(path, []byte(yaml), 0o644); err != nil {
				http.Error(w, "write "+path+": "+err.Error(), http.StatusInternalServerError)
				return
			}
			writeJSON(w, http.StatusOK, map[string]any{
				"path":        abs,
				"yaml":        yaml,
				"probe_count": count,
			})
		default:
			http.Error(w, "GET or POST", http.StatusMethodNotAllowed)
		}
	}
}

// generateBaseline runs every registered probe and serializes the
// results as YAML. Returns (yaml, probeCount). Skipped probes are
// included with expected_status=skipped so the runtime check
// honors the skip rather than treating it as a regression.
func generateBaseline(ctx context.Context, r *Registry) (string, int) {
	probes := r.List()
	// Run any probe that hasn't been run yet; reuse the cached
	// result for probes already run this session (so the operator
	// can curate state via "Run probe" + "Skip" buttons before
	// pressing Export).
	for _, p := range probes {
		if r.LastResult(p.ID()).Status == StatusUnknown {
			r.RunProbe(ctx, p.ID())
		}
	}

	var sb strings.Builder
	host, _ := os.Hostname()
	sb.WriteString("# zerotx-bench hardware baseline.\n")
	sb.WriteString("# Generated by the bench tool's 'Export baseline' button.\n")
	sb.WriteString("# Consumed by the runtime self-check at daemon startup\n")
	sb.WriteString("# (when that feature ships) to detect hardware drift.\n")
	fmt.Fprintf(&sb, "generated: %s\n", time.Now().Format(time.RFC3339))
	fmt.Fprintf(&sb, "host: %s\n", host)
	sb.WriteString("probes:\n")
	for _, p := range probes {
		res := r.LastResult(p.ID())
		fmt.Fprintf(&sb, "  - id: %s\n", yamlString(p.ID()))
		fmt.Fprintf(&sb, "    name: %s\n", yamlString(p.Name()))
		fmt.Fprintf(&sb, "    category: %s\n", yamlString(p.Category()))
		fmt.Fprintf(&sb, "    expected_status: %s\n", res.Status)
		if res.Notes != "" {
			fmt.Fprintf(&sb, "    notes: %s\n", yamlString(res.Notes))
		}
		if len(res.Details) > 0 {
			sb.WriteString("    details:\n")
			keys := make([]string, 0, len(res.Details))
			for k := range res.Details {
				keys = append(keys, k)
			}
			sort.Strings(keys)
			for _, k := range keys {
				fmt.Fprintf(&sb, "      %s: %s\n", yamlString(k), yamlString(res.Details[k]))
			}
		}
	}
	return sb.String(), len(probes)
}

// yamlString renders a string with the minimum quoting needed.
// Quotes if the string contains any of: leading/trailing whitespace,
// control chars, : # ! & * | > ' " { } [ ] , @ ` % or starts with
// something that looks like a number/bool/null. Always-safe: quote.
//
// We pick double-quotes since they support \" escapes for embedded
// quotes; backslashes get doubled. This isn't full YAML 1.2 but
// it's safe for the shapes our probes emit (paths, addresses, fix
// descriptions, short status strings).
func yamlString(s string) string {
	if s == "" {
		return `""`
	}
	// Cheap path: all alphanumeric + a handful of common chars and
	// not a YAML-special keyword.
	plain := true
	for _, c := range s {
		if !(c >= 'a' && c <= 'z') && !(c >= 'A' && c <= 'Z') &&
			!(c >= '0' && c <= '9') && c != '_' && c != '-' && c != '.' &&
			c != '/' && c != ' ' {
			plain = false
			break
		}
	}
	if plain {
		switch strings.ToLower(s) {
		case "yes", "no", "true", "false", "null", "y", "n", "on", "off":
			plain = false
		}
		// Leading/trailing whitespace must be quoted.
		if plain && (strings.HasPrefix(s, " ") || strings.HasSuffix(s, " ")) {
			plain = false
		}
		// Strings that parse as numbers need quoting too.
		if plain && len(s) > 0 && (s[0] == '-' || (s[0] >= '0' && s[0] <= '9')) {
			// Heuristic: if it has only digits / minus / dot, it
			// looks numeric and we should quote.
			numeric := true
			for _, c := range s {
				if !(c >= '0' && c <= '9') && c != '.' && c != '-' && c != '+' && c != 'e' && c != 'E' {
					numeric = false
					break
				}
			}
			if numeric {
				plain = false
			}
		}
	}
	if plain {
		return s
	}
	var out strings.Builder
	out.WriteByte('"')
	for _, c := range s {
		switch c {
		case '\\':
			out.WriteString(`\\`)
		case '"':
			out.WriteString(`\"`)
		case '\n':
			out.WriteString(`\n`)
		case '\r':
			out.WriteString(`\r`)
		case '\t':
			out.WriteString(`\t`)
		default:
			out.WriteRune(c)
		}
	}
	out.WriteByte('"')
	return out.String()
}
